#!/bin/bash

function d_echo() {
    if [ ! -z ${DEBUG} ]; then
        echo "${@}"
    fi
}

function search_part_loopdev () {
    for part in ${loopdev}p*
    do
        d_echo try part=${part}
        if [ "${part_pattern}" == "$(e2label ${part} 2>/dev/null)" ]; then
            partloopdev=${part}
            break
        fi
    done
    d_echo partloopdev=${partloopdev}
}

function mount_part () {
    search_part_loopdev

    [[ -z "${partloopdev}" ]] && echo "error: couldnt set up loopdev for input device image (part_pattern: ${part_pattern})" 1>&2 && exit 1
    mkdir -p /tmp/mount/${part_pattern}
    mount -o loop ${partloopdev} /tmp/mount/${part_pattern}
}

function losetup_image_wic () {
    losetup -fP ${w}
    loopdev=$(losetup | grep ${w} | awk '{print $1}')
    d_echo loopdev=${loopdev}
}

function get_hostname () {
    hostname=$(grep "^hostname" ${1})

    # possibly remove inline comments
    hostname=${hostname%%\#*}

    hostname=$(echo ${hostname} | cut -d "=" -f2 | xargs)
}

function set_hostname () {
    d_echo "set hostname to ${hostname}"
    echo "${hostname}" > /tmp/mount/etc/upper/hostname
    cp /tmp/mount/rootA/etc/hosts /tmp/mount/etc/upper/
    sed -i "s/^127.0.1.1\(.*\)/127.0.1.1 ${hostname}/" /tmp/mount/etc/upper/hosts
}

function config_hostname () {
    get_hostname ${1}
    set_hostname
}
