FROM rust:slim-buster

RUN apt-get update &&  \
    apt-get install -y --no-install-recommends \
        docker.io\
    && apt-get clean && rm -rf /var/lib/apt/lists/* \
    && update-alternatives --set iptables /usr/sbin/iptables-legacy
