hostname = "test-omnect-est"

[provisioning]
source = "dps"
global_endpoint = "https://global.azure-devices-provisioning.net/"
id_scope = "my-scope-id"

[provisioning.attestation]
method = "x509"
registration_id = "test-omnect-est"

[provisioning.attestation.identity_cert]
method = "est"
common_name = "test-omnect-est"

[provisioning.attestation.identity_cert.auto_renew]
rotate_key = true
threshold = "80%"
retry = "4%"

[cert_issuance.est]
trusted_certs = [
     "file:///mnt/cert/ca/ca.crt",
     "file:///mnt/cert/ca/edge_ca.crt",
]

[cert_issuance.est.auth]
bootstrap_identity_cert = "file:///mnt/cert/priv/device_id_cert.pem"
bootstrap_identity_pk = "file:///mnt/cert/priv/device_id_cert_key.pem"            # file URI, or...

[cert_issuance.est.urls]
default = "my-est-url"

[edge_ca]
method = "est"
common_name = "test-omnect-est"
url = "my-est-url"
bootstrap_identity_cert = "file:///mnt/cert/priv/edge_ca_cert.pem"
bootstrap_identity_pk = "file:///mnt/cert/priv/edge_ca_cert_key.pem"

[edge_ca.auto_renew]
rotate_key = true
threshold = "80%"
retry = "4%"
